
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DIE IDENT LPAREN NUMBER PLUS RPAREN TIMESsum : mult PLUS multsum : multmult : NUMBER TIMES valuemult : valuevalue : NUMBER DIE NUMBER\n             | DIE NUMBERvalue : NUMBERvalue : IDENT LPAREN list RPARENvalue : LPAREN sum RPARENlist : sum COMMA sumlist : list COMMA sum'
    
_lr_action_items = {'NUMBER':([0,5,7,8,9,10,12,22,23,],[3,11,3,3,15,17,3,3,3,]),'DIE':([0,3,7,8,9,12,15,22,23,],[5,10,5,5,5,5,10,5,5,]),'IDENT':([0,7,8,9,12,22,23,],[6,6,6,6,6,6,6,]),'LPAREN':([0,6,7,8,9,12,22,23,],[7,12,7,7,7,7,7,7,]),'$end':([1,2,3,4,11,14,15,16,17,20,21,],[0,-2,-7,-4,-6,-1,-7,-3,-5,-9,-8,]),'PLUS':([2,3,4,11,15,16,17,20,21,],[8,-7,-4,-6,-7,-3,-5,-9,-8,]),'RPAREN':([2,3,4,11,13,14,15,16,17,18,20,21,24,25,],[-2,-7,-4,-6,20,-1,-7,-3,-5,21,-9,-8,-11,-10,]),'COMMA':([2,3,4,11,14,15,16,17,18,19,20,21,24,25,],[-2,-7,-4,-6,-1,-7,-3,-5,22,23,-9,-8,-11,-10,]),'TIMES':([3,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sum':([0,7,12,22,23,],[1,13,19,24,25,]),'mult':([0,7,8,12,22,23,],[2,2,14,2,2,2,]),'value':([0,7,8,9,12,22,23,],[4,4,4,16,4,4,4,]),'list':([12,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sum","S'",1,None,None,None),
  ('sum -> mult PLUS mult','sum',3,'p_add','zach.py',120),
  ('sum -> mult','sum',1,'p_no_add','zach.py',124),
  ('mult -> NUMBER TIMES value','mult',3,'p_mult','zach.py',128),
  ('mult -> value','mult',1,'p_no_mult','zach.py',132),
  ('value -> NUMBER DIE NUMBER','value',3,'p_die','zach.py',136),
  ('value -> DIE NUMBER','value',2,'p_die','zach.py',137),
  ('value -> NUMBER','value',1,'p_literal','zach.py',141),
  ('value -> IDENT LPAREN list RPAREN','value',4,'p_function','zach.py',145),
  ('value -> LPAREN sum RPAREN','value',3,'p_parens','zach.py',154),
  ('list -> sum COMMA sum','list',3,'p_list_new','zach.py',158),
  ('list -> list COMMA sum','list',3,'p_list_append','zach.py',162),
]
